DEFAULT_FOLDER = lily58_my/right
# MCU name
MCU = RP2040

# Bootloader selection
BOOTLOADER = rp2040
SERIAL_DRIVER = vendor

# Via/Vial
VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = yes
OLED_DRIVER = ssd1306
RGB_MATRIX_ENABLE = yes

OLED_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
WPM_ENABLE = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
GRAVE_ESC_ENABLE = yes
MAGIC_ENABLE = yes
BOOTMAGIC_ENABLE = yes


ENCODER_MAP_ENABLE = yes
ENCODER_ENABLE = yes
NKRO_ENABLE = no

COMMAND_ENABLE = no
CONSOLE_ENABLE = no

QMK_SETTINGS = yes
LTO_ENABLE = yes

KEY_OVERRIDE_ENABLE = yes
